### ISSUE TITLE
Humble Bundle tools includes titles with revealed giftlinks in 'unredeemed' list

### ISSUE THREAD

**Issue by cowbutt** [mmarcincin/userscripts#1]
This change fixes it:

						//if (gameTable[i].parentNode.getElementsByClassName("keyfield redeemed").length === 0) { gameList.push(addString); } //cowbutt
                        if ((gameTable[i].parentNode.getElementsByClassName("keyfield redeemed").length === 0) && (gameTable[i].parentNode.getElementsByClassName("keyfield redeemed-gift").length === 0)) { gameList.push(addString); } //cowbutt

**Comment by mmarcincin** [comment]
Sorry for late reply, I added it to version 0.0.2.9.
